services:
  agent:
    env_file: [.env]
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run'
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  mongo:
    command: mongod
    image: mongo:4.0.0

  api-gateway:
    build:
      context: ./api_gateway/
    restart: on-failure
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./api_gateway/.env
    depends_on:
      - postgres
      - badlisted-words
#    volumes:
#      - ./app:./app

  postgres:
    image: postgres:13.0-alpine
    restart: on-failure
    ports:
      - "5433:5432"
    env_file:
      - ./api_gateway/.env
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
version: '3.7'
