"""initial table

Revision ID: 929604e1acdc
Revises: 
Create Date: 2022-10-31 02:01:28.571954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929604e1acdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badlisted_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badlisted_words')
    # ### end Alembic commands ###
